INSERT INTO Alergen ([Order], Title, Description) VALUES (1, 'Milk', 'Milk');
INSERT INTO Alergen ([Order], Title, Description) VALUES (2, 'Eggs', 'Eggs');
INSERT INTO Alergen ([Order], Title, Description) VALUES (3, 'Fish', 'Fish');
INSERT INTO Alergen ([Order], Title, Description) VALUES (4, 'Peanuts', 'Peanuts');
INSERT INTO Alergen ([Order], Title, Description) VALUES (5, 'Soy', 'Soy');
INSERT INTO Alergen ([Order], Title, Description) VALUES (6, 'Wheat', 'Wheat');
INSERT INTO Alergen ([Order], Title, Description) VALUES (7, 'Tree Nuts', 'Tree Nuts');
INSERT INTO Alergen ([Order], Title, Description) VALUES (8, 'Shellfish', 'Shellfish');

INSERT INTO Ingredient (Title, Description, Category) VALUES ('Onion', 'Onion', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Garlic', 'Garlic', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Tomato', 'Tomato', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Olives', 'Olives', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Chilli', 'Chilli', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Pepper', 'Pepper', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Spinach', 'Spinach', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Mushrooms', 'Mushrooms', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Sweetcorn', 'Sweetcorn', 'Vegetable');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Pineapple', 'Pineapple', 'Fruit');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Tuna', 'Tuna', 'Fish');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Salmon', 'Salmon', 'Fish');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Prawns', 'Prawns', 'Fish');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Anchovies', 'Anchovies', 'Fish');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Ham', 'Ham', 'Meat');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Bacon', 'Bacon', 'Meat');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Chicken', 'Chicken', 'Meat');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Chorizo', 'Chorizo', 'Meat');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Pepperoni', 'Pepperoni', 'Meat');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Prosciutto', 'Prosciutto', 'Meat');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Gouda', 'Gouda', 'Dairy');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Burrata', 'Burrata', 'Dairy');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Cheddar', 'Cheddar', 'Dairy');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Ricotta', 'Ricotta', 'Dairy');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Parmesan', 'Parmesan', 'Dairy');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Camembert', 'Camembert', 'Dairy');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Gorgonzola', 'Gorgonzola', 'Dairy');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Mozzarella', 'Mozzarella', 'Dairy');
INSERT INTO Ingredient (Title, Description, Category) VALUES ('Goat Cheese', 'Goat Cheese', 'Dairy');

INSERT INTO Address (Street, HouseNumber, City, PostalCode, Country, AddressId) VALUES ('Vršovická', '25', 'Praha', '101 00', 'Czech', '1');
INSERT INTO Address (Street, HouseNumber, City, PostalCode, Country, AddressId) VALUES ('Gruzínská', '16', 'Praha', '101 00', 'Czech', '1');
INSERT INTO Address (Street, HouseNumber, City, PostalCode, Country, AddressId) VALUES ('Korunní', '810', 'Praha', '101 00', 'Czech', '2');
INSERT INTO Address (Street, HouseNumber, City, PostalCode, Country, AddressId) VALUES ('Vinohradská', '25', 'Praha', '101 00', 'Czech', '3');

INSERT INTO CustomerContact (CustomerName, PhoneNumber, Email) VALUES ('John Doe', '+420 123 456 789', 'michal@gmail.com');
INSERT INTO CustomerContact (CustomerName, PhoneNumber, Email) VALUES ('John Doe', '+420 123 456 789', 'ales@gmail.com');
INSERT INTO CustomerContact (CustomerName, PhoneNumber, Email) VALUES ('John Doe', '+420 123 456 789', 'jana@gmail.com');
INSERT INTO CustomerContact (CustomerName, PhoneNumber, Email) VALUES ('John Doe', '+420 123 456 789', 'katerina@gmail.com');

INSERT INTO MenuItem (Title, Description, Price) VALUES ('Margherita', 'Tomato sauce, mozzarella, basil', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Marinara', 'Tomato sauce, garlic', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Quattro Stagioni', 'Tomato sauce, mozzarella, mushrooms, ham, artichokes, olives, oregano', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Carbonara', 'Tomato sauce, mozzarella, parmesan, eggs, bacon', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Frutti di Mare', 'Tomato sauce, seafood', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Quattro Formaggi', 'Tomato sauce, mozzarella, parmesan, gorgonzola cheese, artichokes, olives, oregano', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Crudo', 'Tomato sauce, mozzarella, prosciutto, mushrooms', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Napoletana', 'Tomato sauce, mozzarella, anchovies, oregano', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Pugliese', 'Tomato sauce, mozzarella, onions, capers, olives', 100);
INSERT INTO MenuItem (Title, Description, Price) VALUES ('Montanara', 'Tomato sauce, mozzarella, mushrooms, pepperoni, ricotta cheese', 100);